
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        image: docker.io/takehome-scheduler:latest
        imagePullPolicy: Never
        command: ["/usr/local/bin/custom-scheduler"]
        args:
        - "--scheduler-name=my-custom-scheduler"
        - "--namespace=default"
      serviceAccountName: custom-scheduler